// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB5Vo2Wzd_YlzyCkdddXs772FZbRn1ffk',
    appId: '1:671213478521:web:7eaed3b2b4116f3ac42aa8',
    messagingSenderId: '671213478521',
    projectId: 'flutterconverse',
    authDomain: 'flutterconverse.firebaseapp.com',
    storageBucket: 'flutterconverse.appspot.com',
    measurementId: 'G-GS7KST3EPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ou5eTujc1ZB-cmagcorkb4fnH_D7nSg',
    appId: '1:671213478521:android:20bde9459db6f0ddc42aa8',
    messagingSenderId: '671213478521',
    projectId: 'flutterconverse',
    storageBucket: 'flutterconverse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqq387yvv9AXuGX3yzoI4AFHgUItohG-Q',
    appId: '1:671213478521:ios:670835d51b91d01ec42aa8',
    messagingSenderId: '671213478521',
    projectId: 'flutterconverse',
    storageBucket: 'flutterconverse.appspot.com',
    iosClientId: '671213478521-3f5qbdlgkkqv39ud55mm0v0j75filj4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterConverse',
  );
}
